version: '3.9'

services:

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: docker/production/Dockerfile
    restart: always
    env_file:
      - ./.env.production
    ports:
      - 5173:80
    depends_on:
      - server
    networks:
      - queue-net

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: docker/production/Dockerfile
    env_file:
      - ./.env.production
    ports:
      - '5000:5000'
    networks:
      - queue-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      
      # - /etc/letsencrypt/live/test.localhost/fullchain.pem:/etc/letsencrypt/live/test.localhost/fullchain.pem:ro
      # - /etc/letsencrypt/live/test.localhost/privkey.pem:/etc/letsencrypt/live/test.localhost/privkey.pem:ro

      - ./nginx/certificates:/etc/nginx/certificates:rw 
    restart: always
    networks:
      - queue-net
    depends_on:
      - server
      - client
      
networks:
  queue-net:
    driver: bridge
